name: Flutter CI/CD Pipeline

on:
  push:
    branches: [ master1 ]
  pull_request:
    branches: [ master1 ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Analyze code
      run: flutter analyze --no-fatal-warnings
      continue-on-error: true
    
    - name: Run tests
      run: flutter test
      continue-on-error: true

  build-android:
    name: Build Signed AAB for Play Store
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master1'
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.0'
        channel: 'stable'
    
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Create keystore directory
      run: mkdir -p android/app/keystore
    
    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore/upload-keystore.jks
    
    - name: Create key.properties
      run: |
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=keystore/upload-keystore.jks" >> android/key.properties
    
    - name: Build Signed Release AAB
      run: flutter build appbundle --release
    
    - name: Upload Signed AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-release-signed-aab
        path: build/app/outputs/bundle/release/app-release.aab
